# .github/workflows/deploy.yml
name: Deploy Next.js App on Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/t3_tutorial:latest
                build-args: |
                    DATABASE_URL_BUILD=${{ secrets.DATABASE_URL_BUILD }}

            - name: Notify Server for Deployment
              run: |
                curl -X POST -H "Content-Type: application/json" -H "X-Deployment-Secret: ${{ secrets.DEPLOYMENT_SECRET }}" \
                http://91.107.217.2:8080/deploy
              env:
                DE_DEPLOYMENT_SECRET: ${{ secrets.DEPLOYMENT_SECRET }}


